name: Deploy to Kubernetes

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Build and Push
      run: |
        docker build -t public.ecr.aws/a9o4o2s3/jack-backend:${{ github.sha }} .
        docker tag public.ecr.aws/a9o4o2s3/jack-backend:${{ github.sha }} public.ecr.aws/a9o4o2s3/jack-backend:latest
        docker push public.ecr.aws/a9o4o2s3/jack-backend:${{ github.sha }}
        docker push public.ecr.aws/a9o4o2s3/jack-backend:latest

    - name: Update Kubernetes
      run: |
        aws eks update-kubeconfig --name your-cluster-name --region us-east-1
        kubectl rollout restart deployment/jack-trades-backend -n jack-trades-ns
        kubectl rollout status deployment/jack-trades-backend -n jack-trades-ns
