FROM node:18-alpine AS builder

WORKDIR /app

COPY client/package*.json ./ 
RUN npm ci

COPY client ./
ENV NODE_OPTIONS="--max-old-space-size=2048"
RUN npm run build

# Use nginx to serve React
FROM nginx:alpine AS production
COPY --from=builder /app/build /usr/share/nginx/html
COPY client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
